zones = {"Abbey Road": 2.5,
"Acton Central": 3,
"Acton Main Line": 3,
"Acton Town": 3,
"Addington Village": 0,
"Addiscombe": 0,
"Aldgate": 1,
"Aldgate East": 1,
"All Saints": 2,
"Alperton": 4,
"Amersham": 9,
"Ampere Way": 0,
"Anerley": 4,
"Angel": 1,
"Archway": 2.5,
"Arena": 0,
"Arnos Grove": 4,
"Arsenal": 2,
"Avenue Road": 0,
"Baker Street": 1,
"Balham": 3,
"Bank": 1,
"Barbican": 1,
"Barking": 4,
"Barkingside": 4,
"Barons Court": 2,
"Bayswater": 1,
"Beckenham Junction": 0,
"Beckenham Road": 0,
"Beckton": 3,
"Beckton Park": 3,
"Becontree": 5,
"Beddington Lane": 0,
"Belgrave Walk": 0,
"Belsize Park": 2,
"Bermondsey": 2,
"Bethnal Green": 2,
"Birkbeck": 0,
"Blackfriars": 1,
"Blackhorse Lane": 0,
"Blackhorse Road": 3,
"Blackwall": 2,
"Bond Street": 1,
"Borough": 1,
"Boston Manor": 4,
"Bounds Green": 3.5,
"Bow Church": 2,
"Bow Road": 2,
"Brent Cross": 3,
"Brentwood": 9,
"Brixton": 2,
"Brockley": 2,
"Bromley-by-Bow": 2.5,
"Brondesbury": 2,
"Brondesbury Park": 2,
"Bruce Grove": 3,
"Buckhurst Hill": 5,
"Burnt Oak": 4,
"Bush Hill Park": 5,
"Bushey": 8,
"Caledonian Road": 2,
"Caledonian Road & Barnsbury": 2,
"Cambridge Heath": 2,
"Camden Road": 2,
"Camden Town": 2,
"Canada Water": 2,
"Canary Wharf": 2,
"Canning Town": 2.5,
"Cannon Street": 1,
"Canonbury": 2,
"Canons Park": 5,
"Carpenders Park": 7,
"Centrale": 0,
"Chadwell Heath": 5,
"Chalfont & Latimer": 8,
"Chalk Farm": 2,
"Chancery Lane": 1,
"Charing Cross": 1,
"Chesham": 9,
"Cheshunt": 8,
"Chigwell": 4,
"Chingford": 5,
"Chiswick Park": 3,
"Chorleywood": 7,
"Church Street": 0,
"Clapham Common": 2,
"Clapham High Street": 2,
"Clapham Junction": 2,
"Clapham North": 2,
"Clapham South": 2.5,
"Clapton": 2.5,
"Cockfosters": 5,
"Colindale": 4,
"Colliers Wood": 3,
"Coombe Lane": 0,
"Covent Garden": 1,
"Crossharbour": 2,
"Crouch Hill": 3,
"Croxley": 7,
"Crystal Palace": 3.5,
"Custom House for ExCel": 3,
"Cutty Sark for Maritime Greenwich": 2.5,
"Cyprus": 3,
"Dagenham East": 5,
"Dagenham Heathway": 5,
"Dalston Junction": 2,
"Dalston Kingsland": 2,
"Debden": 6,
"Denmark Hill": 2,
"Deptford Bridge": 2.5,
"Devons Road": 2,
"Dollis Hill": 3,
"Dundonald Road": 0,
"Ealing Broadway": 3,
"Ealing Common": 3,
"Earl's Court": 1.5,
"East Acton": 2,
"East Croydon": 0,
"East Finchley": 3,
"East Ham": 3.5,
"East India": 2.5,
"East Putney": 2.5,
"Eastcote": 5,
"Edgware": 5,
"Edgware Road": 1,
"Edmonton Green": 4,
"Elephant & Castle": 1.5,
"Elm Park": 6,
"Elmers End": 0,
"Elverson Road": 2.5,
"Embankment": 1,
"Emerson Park": 6,
"Emirates Greenwich Penisula": 0,
"Emirates Royal Docks": 0,
"Enfield Town": 5,
"Epping": 6,
"Euston": 1,
"Euston Square": 1,
"Fairlop": 4,
"Farringdon": 1,
"Fieldway": 0,
"Finchley Central": 4,
"Finchley Road": 2,
"Finchley Road & Frognal": 2,
"Finsbury Park": 2,
"Forest Gate": 3,
"Forest Hill": 3,
"Fulham Broadway": 2,
"Gallions Reach": 3,
"Gants Hill": 4,
"George Street": 0,
"Gidea Park": 6,
"Gloucester Road": 1,
"Golders Green": 3,
"Goldhawk Road": 2,
"Goodge Street": 1,
"Goodmayes": 4,
"Gospel Oak": 2,
"Grange Hill": 4,
"Gravel Hill": 0,
"Great Portland Street": 1,
"Green Park": 1,
"Greenford": 4,
"Greenwich": 2.5,
"Gunnersbury": 3,
"Hackney Central": 2,
"Hackney Downs": 2,
"Hackney Wick": 2,
"Haggerston": 2,
"Hainault": 4,
"Hammersmith": 2,
"Hampstead": 2.5,
"Hampstead Heath": 2,
"Hanger Lane": 3,
"Hanwell": 4,
"Harlesden": 3,
"Harold Wood": 6,
"Harringay Green Lanes": 3,
"Harrington Road": 0,
"Harrow & Wealdstone": 5,
"Harrow-on-the-Hill": 5,
"Hatch End": 6,
"Hatton Cross": 5.5,
"Hayes & Harlington": 5,
"Headstone Lane": 5,
"Heathrow Terminal 4": 6,
"Heathrow Terminal 5": 6,
"Heathrow Terminals 2 & 3": 6,
"Hendon Central": 3.5,
"Heron Quays": 2,
"High Barnet": 5,
"High Street Kensington": 1,
"Highams Park": 4,
"Highbury & Islington": 2,
"Highgate": 3,
"Hillingdon": 6,
"Holborn": 1,
"Holland Park": 2,
"Holloway Road": 2,
"Homerton": 2,
"Honor Oak Park": 3,
"Hornchurch": 6,
"Hounslow Central": 4,
"Hounslow East": 4,
"Hounslow West": 5,
"Hoxton": 1.5,
"Hyde Park Corner": 1,
"Ickenham": 6,
"Ilford": 4,
"Imperial Wharf": 2,
"Island Gardens": 2,
"Kennington": 2,
"Kensal Green": 2,
"Kensal Rise": 2,
"Kensington (Olympia)": 2,
"Kentish Town": 2,
"Kentish Town West": 2,
"Kenton": 4,
"Kew Gardens": 3.5,
"Kilburn": 2,
"Kilburn High Road": 2,
"Kilburn Park": 2,
"King George V": 3,
"King Henry's Drive": 0,
"King's Cross St Pancras": 1,
"Kingsbury": 4,
"Knightsbridge": 1,
"Ladbroke Grove": 2,
"Lambeth North": 1,
"Lancaster Gate": 1,
"Langdon Park": 2,
"Latimer Road": 2,
"Lebanon Road": 0,
"Leicester Square": 1,
"Lewisham": 2.5,
"Leyton": 3,
"Leyton Midland Road": 3,
"Leytonstone": 3.5,
"Leytonstone High Road": 3,
"Limehouse": 2,
"Liverpool Street": 1,
"Lloyd Park": 0,
"London Bridge": 1,
"London City Airport": 3,
"London Fields": 2,
"Loughton": 6,
"Maida Vale": 2,
"Manor House": 2.5,
"Manor Park": 3.5,
"Mansion House": 1,
"Marble Arch": 1,
"Maryland": 3,
"Marylebone": 1,
"Merton Park": 0,
"Mile End": 2,
"Mill Hill East": 4,
"Mitcham": 0,
"Mitcham Junction": 0,
"Monument": 1,
"Moor Park": 6.5,
"Moorgate": 1,
"Morden": 4,
"Morden Road": 0,
"Mornington Crescent": 2,
"Mudchute": 2,
"Neasden": 3,
"New Addington": 0,
"New Cross": 2,
"New Cross Gate": 2,
"Newbury Park": 4,
"North Acton": 2.5,
"North Ealing": 3,
"North Greenwich": 2.5,
"North Harrow": 5,
"North Wembley": 4,
"Northfields": 3,
"Northholt": 5,
"Northwick Park": 4,
"Northwood": 6,
"Northwood Hills": 6,
"Norwood Junction": 4,
"Notting Hill Gate": 1.5,
"Oakwood": 5,
"Old Street": 1,
"Osterley": 4,
"Oval": 2,
"Oxford Circus": 1,
"Paddington": 1,
"Park Royal": 3,
"Parsons Green": 2,
"Peckham Rye": 2,
"Penge West": 4,
"Perivale": 4,
"Phipps Bridge": 0,
"Piccadilly Circus": 1,
"Pimlico": 1,
"Pinner": 5,
"Plaistow": 3,
"Pontoon Dock": 3,
"Poplar": 2,
"Preston Road": 4,
"Prince Regent": 3,
"Pudding Mill Lane": 2.5,
"Putney Bridge": 2,
"Queen's Park": 2,
"Queens Road Peckham": 2,
"Queensbury": 4,
"Queensway": 1,
"Ravenscourt Park": 2,
"Rayners Lane": 5,
"Rectory Road": 2,
"Redbridge": 4,
"Reeves Corner": 0,
"Regent's Park": 1,
"Richmond": 4,
"Rickmansworth": 7,
"Roding Valley": 4,
"Romford": 6,
"Rotherhithe": 2,
"Royal Albert": 3,
"Royal Oak": 2,
"Royal Victoria": 3,
"Ruislip": 6,
"Ruislip Gardens": 5,
"Ruislip Manor": 6,
"Russell Square": 1,
"Sandilands": 0,
"Seven Kings": 4,
"Seven Sisters": 3,
"Shadwell": 2,
"Shenfield": 0,
"Shepherd's Bush": 2,
"Shepherd's Bush Market": 2,
"Shoreditch High Street": 1,
"Silver Street": 4,
"Sloane Square": 1,
"Snaresbrook": 4,
"South Acton": 3,
"South Ealing": 3,
"South Hampstead": 2,
"South Harrow": 5,
"South Kensington": 1,
"South Kenton": 4,
"South Quay": 2,
"South Ruislip": 5,
"South Tottenham": 3,
"South Wimbledon": 3.5,
"South Woodford": 4,
"Southall": 4,
"Southbury": 5,
"Southfields": 3,
"Southgate": 4,
"Southwark": 1,
"St James Street": 3,
"St James's Park": 1,
"St John's Wood": 2,
"St Paul's": 1,
"Stamford Brook": 2,
"Stamford Hill": 3,
"Stanmore": 5,
"Star Lane": 2.5,
"Stepney Green": 2,
"Stockwell": 2,
"Stoke Newington": 2,
"Stonebridge Park": 3,
"Stratford": 2.5,
"Stratford High Street": 2.5,
"Stratford International": 2.5,
"Sudbury Hill": 4,
"Sudbury Town": 4,
"Surrey Quays": 2,
"Swiss Cottage": 2,
"Sydenham": 3,
"Temple": 1,
"Theobalds Grove": 7,
"Therapia Lane": 0,
"Theydon Bois": 6,
"Tooting Bec": 3,
"Tooting Broadway": 3,
"Tottenham Court Road": 1,
"Tottenham Hale": 3,
"Totteridge & Whetstone": 4,
"Tower Gateway": 1,
"Tower Hill": 1,
"Tufnell Park": 2,
"Turkey Street": 6,
"Turnham Green": 2.5,
"Turnpike Lane": 3,
"Upminster": 6,
"Upminster Bridge": 6,
"Upney": 4,
"Upper Holloway": 2,
"Upton Park": 3,
"Uxbridge": 6,
"Vauxhall": 1.5,
"Victoria": 1,
"Waddon Marsh": 0,
"Walthamstow Central": 3,
"Walthamstow Queen's Road": 3,
"Wandle Park": 0,
"Wandsworth Road": 2,
"Wanstead": 4,
"Wanstead Park": 3,
"Wapping": 2,
"Warren Street": 1,
"Warwick Avenue": 2,
"Waterloo": 1,
"Watford": 7,
"Watford High Street": 8,
"Watford Junction": 0,
"Wellesley Road": 0,
"Wembley Central": 4,
"Wembley Park": 4,
"West Acton": 3,
"West Brompton": 2,
"West Croydon": 5,
"West Ealing": 3,
"West Finchley": 4,
"West Ham": 2.5,
"West Hampstead": 2,
"West Harrow": 5,
"West India Quay": 2,
"West Kensington": 2,
"West Ruislip": 6,
"West Silvertown": 3,
"Westbourne Park": 2,
"Westferry": 2,
"Westminster": 1,
"White City": 2,
"White Hart Lane": 3,
"Whitechapel": 2,
"Willesden Green": 2.5,
"Willesden Junction": 2.5,
"Wimbledon": 3,
"Wimbledon Park": 3,
"Wood Green": 3,
"Wood Lane": 2,
"Wood Street": 4,
"Woodford": 4,
"Woodgrange Park": 3.5,
"Woodside": 0,
"Woodside Park": 4,
"Woolwich Arsenal": 4}